name: TypeScript

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
        

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '>=16'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build